"""Execution service for the AI-assisted ``report.simple`` protocol.

The standard and legacy workflows keep their own state machines.  This module
owns only the AI-assisted Simple protocol and enforces its contract:

* every business step is generated by a reused production skill and stored as
  an immutable :class:`SimpleStepRevision`;
* consultants review the exact revision they were shown, and approving writes
  an immutable :class:`SimpleReviewDecision`;
* stale activation numbers, stale base revisions and stale input fingerprints
  are rejected instead of silently overwriting newer work;
* reopening a completed step invalidates the downstream revisions that actually
  referenced the replaced confirmation.

Phase 1 deliberately keeps node prompts and per-node output schemas out of
scope: a run result is mapped onto the generic revision contract
``content + structured_content + source_revision_refs``.
"""

from copy import deepcopy
from datetime import datetime
import hashlib
import json
from typing import Any, Optional

from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm.attributes import flag_modified

from app.core.time import utc_now_naive
from app.domains.audit.context import AuditContext
from app.domains.audit.service import record_audit
from app.domains.delivery.simple_models import (
    SimpleReviewDecision,
    SimpleStepExecution,
    SimpleStepRevision,
)
from app.domains.skills.models import SkillRun
from app.domains.workflow.models import ReportCase, StepTask, WorkflowInstance
from app.domains.workflow.definitions import report_step_catalog
from app.domains.workflow.service import (
    complete_step,
    enqueue_step_ready,
    lock_case_and_tasks,
)
from app.domains.workflow.simple_definitions import (
    SIMPLE_PROTOCOL_AI_ASSISTED,
    case_simple_protocol,
    step_simple_step_config,
)
from app.models.user import User

SIMPLE_STEP_TARGET_TYPE = "SIMPLE_STEP"

INITIAL = "INITIAL"
AI_REVISION = "AI_REVISION"
REGENERATE = "REGENERATE"
MANUAL_EDIT = "MANUAL_EDIT"

_RUNNING_STATUS_BY_REVISION_TYPE = {
    INITIAL: "GENERATING",
    AI_REVISION: "REVISING",
    REGENERATE: "REVISING",
}

_RUN_TYPE_BY_REVISION_TYPE = {
    INITIAL: "INITIAL",
    AI_REVISION: "REWRITE",
    REGENERATE: "REGENERATE",
}

_CONTENT_KEYS = ("content", "report_text", "markdown", "text")

# Decision 7: the first attempt plus two automatic retries; anything beyond
# that stays FAILED and waits for an explicit consultant retry.
SIMPLE_AUTO_RETRY_LIMIT = 2


def _now() -> datetime:
    return utc_now_naive()


def _fingerprint(payload: dict[str, Any]) -> str:
    encoded = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


_UNSET: Any = object()


def _normalized_text(value: Any) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _expected_reviewer_id(
    review_mode: str,
    actor: User,
    on_behalf_of_user_id: Optional[int],
    reviewer_id: Optional[int] = None,
) -> int:
    if review_mode != "OWNER" and reviewer_id is None:
        return on_behalf_of_user_id  # type: ignore[return-value]
    return reviewer_id or actor.id


def _require_ai_case(report_case: ReportCase) -> None:
    if case_simple_protocol(report_case) != SIMPLE_PROTOCOL_AI_ASSISTED:
        raise ValueError("simple_ai_protocol_required")


def _find_step(tasks: list[StepTask], step_key: str) -> StepTask:
    for task in tasks:
        if task.step_key == step_key:
            return task
    raise ValueError("step_task_not_found")


def _step_name(step_key: str) -> str:
    for step in report_step_catalog():
        if step["step_key"] == step_key:
            return str(step.get("name") or step_key)
    return step_key


async def _lock_case(
    db: AsyncSession, case_id: int
) -> tuple[ReportCase, WorkflowInstance, list[StepTask]]:
    report_case, instance, tasks = await lock_case_and_tasks(db, case_id)
    _require_ai_case(report_case)
    return report_case, instance, tasks


async def _lock_execution(
    db: AsyncSession, report_case: ReportCase, task: StepTask
) -> SimpleStepExecution:
    execution = await db.scalar(
        select(SimpleStepExecution)
        .where(
            SimpleStepExecution.report_case_id == report_case.id,
            SimpleStepExecution.step_key == task.step_key,
        )
        .with_for_update()
    )
    if execution is None:
        raise ValueError("simple_step_execution_not_found")
    if task.activation_no > 0 and execution.activation_no != task.activation_no:
        raise ValueError("simple_activation_outdated")
    return execution


def _authorize_actor(task: StepTask, actor: User) -> None:
    if actor.role == "admin":
        return
    if actor.role != "consultant" or task.assignee_id != actor.id:
        raise ValueError("report_case_forbidden")


async def _resolve_review_identity(
    db: AsyncSession,
    task: StepTask,
    actor: User,
    *,
    review_mode: Optional[str] = None,
    on_behalf_of_user_id: Optional[int] = None,
) -> tuple[str, Optional[int]]:
    """Resolve the attributed reviewer separately from the operator.

    Consultants may only act as themselves.  Administrators always act with
    an explicit audit identity, defaulting to the current step owner; choosing
    ``DELEGATED`` requires the caller to name the attributed reviewer.
    """
    if actor.role == "admin":
        resolved_mode = (review_mode or "ADMIN").upper()
        if resolved_mode not in {"ADMIN", "DELEGATED"}:
            raise ValueError("simple_review_forbidden")
        target_id = (
            on_behalf_of_user_id
            if resolved_mode == "DELEGATED"
            else (on_behalf_of_user_id or task.assignee_id)
        )
        if not isinstance(target_id, int) or target_id <= 0:
            raise ValueError("simple_review_delegation_required")
        target = await db.get(User, target_id)
        if target is None or not target.is_active:
            raise ValueError("simple_review_target_not_found")
        return resolved_mode, target_id
    _authorize_actor(task, actor)
    if review_mode not in (None, "OWNER") or on_behalf_of_user_id is not None:
        raise ValueError("simple_review_forbidden")
    return "OWNER", None


def _fingerprint_scope(
    report_case: ReportCase,
    task: StepTask,
    execution: SimpleStepExecution,
    base_revision: Optional[SimpleStepRevision],
    feedback_text: Optional[str],
    upstream: dict[str, dict[str, Any]],
    *,
    revision_type: str,
    recover_stale: bool,
) -> dict[str, Any]:
    config = task.config_snapshot or {}
    return {
        "case_snapshot": report_case.application_snapshot or {},
        "step_key": task.step_key,
        "activation_no": execution.activation_no,
        "assignee_id": task.assignee_id,
        "revision_type": revision_type,
        "input_contract": config.get("input_contract"),
        "skill_version_id": config.get("skill_version_id"),
        "generation_profile": config.get("generation_profile"),
        "base_revision_id": base_revision.id if base_revision else None,
        "upstream_revision_ids": {
            key: value.get("revision_id")
            for key, value in sorted(upstream.items())
            if isinstance(value, dict)
        },
        "feedback_text": feedback_text,
        "recover_stale": recover_stale,
    }


def _revision_payload(run: SkillRun) -> tuple[str, Optional[dict]]:
    """Map one completed skill run onto the generic revision contract."""
    output = run.output_parsed if isinstance(run.output_parsed, dict) else None
    structured = deepcopy(output) if isinstance(output, dict) else None
    content: Optional[str] = None
    if isinstance(output, dict):
        for key in _CONTENT_KEYS:
            value = output.get(key)
            if isinstance(value, str) and value.strip():
                content = value
                break
    if content is None and isinstance(run.output_raw, str) and run.output_raw.strip():
        content = run.output_raw
    if content is None and structured:
        content = json.dumps(structured, ensure_ascii=False, sort_keys=True, indent=2)
    return (content or "").strip(), structured


async def _next_revision_no(db: AsyncSession, execution_id: int) -> int:
    latest = await db.scalar(
        select(func.max(SimpleStepRevision.revision_no)).where(
            SimpleStepRevision.execution_id == execution_id
        )
    )
    return int(latest or 0) + 1


async def _base_revision(
    db: AsyncSession,
    execution: SimpleStepExecution,
    base_revision_id: Optional[int],
) -> Optional[SimpleStepRevision]:
    if base_revision_id is None:
        return None
    revision = await db.get(SimpleStepRevision, base_revision_id)
    if revision is None or revision.execution_id != execution.id:
        raise ValueError("simple_revision_not_found")
    return revision


async def _retry_parameters(
    db: AsyncSession, execution: SimpleStepExecution
) -> tuple[str, Optional[SimpleStepRevision], Optional[str], int, dict]:
    """Rebuild the frozen input of a failed run so a retry is deterministic."""
    snapshot = execution.input_snapshot or {}
    revision_type = snapshot.get("revision_type")
    if revision_type not in {INITIAL, AI_REVISION, REGENERATE}:
        revision_type = INITIAL
    base_id = (snapshot.get("base_revision") or {}).get("revision_id")
    base = (
        await _base_revision(db, execution, base_id)
        if isinstance(base_id, int)
        else None
    )
    attempt_no = snapshot.get("attempt_no")
    if not isinstance(attempt_no, int) or attempt_no < 1:
        attempt_no = 1
    upstream = snapshot.get("upstream_revisions")
    return (
        revision_type,
        base,
        snapshot.get("feedback_text"),
        attempt_no,
        upstream if isinstance(upstream, dict) else {},
    )


async def _load_upstream_revisions(
    db: AsyncSession, report_case: ReportCase, tasks: list[StepTask], task: StepTask
) -> dict[str, dict[str, Any]]:
    upstream: dict[str, dict[str, Any]] = {}
    earlier = [item for item in tasks if item.sequence_no < task.sequence_no]
    if not earlier:
        return upstream
    executions = list(
        await db.scalars(
            select(SimpleStepExecution).where(
                SimpleStepExecution.report_case_id == report_case.id,
                SimpleStepExecution.step_key.in_([item.step_key for item in earlier]),
            )
        )
    )
    by_key = {item.step_key: item for item in executions}
    revision_ids = [
        item.confirmed_revision_id
        for item in executions
        if item.confirmed_revision_id is not None
    ]
    revisions = {}
    if revision_ids:
        revisions = {
            revision.id: revision
            for revision in await db.scalars(
                select(SimpleStepRevision).where(
                    SimpleStepRevision.id.in_(revision_ids)
                )
            )
        }
    for item in earlier:
        execution = by_key.get(item.step_key)
        if execution is None or execution.confirmed_revision_id is None:
            continue
        revision = revisions.get(execution.confirmed_revision_id)
        if revision is None:
            continue
        upstream[item.step_key] = {
            "revision_id": revision.id,
            "revision_no": revision.revision_no,
            "content": revision.content,
            "structured_content": revision.structured_content,
        }
    return upstream


async def _resolve_retry_parameters(
    db: AsyncSession,
    report_case: ReportCase,
    tasks: list[StepTask],
    execution: SimpleStepExecution,
    task: StepTask,
) -> tuple[str, Optional[SimpleStepRevision], Optional[str], int, dict, bool]:
    """Rebuild the frozen retry plan of a failed Simple run.

    The returned ``recover_stale`` flag marks the plan as a recovery against
    the latest confirmed upstream revisions, which is the only legal way out
    of a stale dependency chain.
    """
    revision_type, base, feedback, attempt_no, _frozen_upstream = (
        await _retry_parameters(db, execution)
    )
    if execution.dependency_status == "STALE":
        # A stale revision must be rebuilt from the currently confirmed
        # upstream revisions, never from the snapshot that referenced the
        # replaced confirmation.
        revision_type = REGENERATE if execution.current_revision_id else INITIAL
        base = await _base_revision(db, execution, execution.current_revision_id)
        upstream = await _load_upstream_revisions(db, report_case, tasks, task)
        return revision_type, base, None, attempt_no, upstream, True
    if revision_type == AI_REVISION and not (feedback or "").strip():
        # Revising without feedback would silently degrade into a regeneration.
        revision_type = REGENERATE
    return revision_type, base, feedback, attempt_no, _frozen_upstream, False


async def _latest_failed_run_for_retry(
    db: AsyncSession, task: StepTask
) -> Optional[SkillRun]:
    """Return the failed run whose frozen plan the next attempt must reuse."""
    run = await db.scalar(
        select(SkillRun)
        .where(
            SkillRun.target_type == SIMPLE_STEP_TARGET_TYPE,
            SkillRun.step_task_id == task.id,
            SkillRun.status == "FAILED",
        )
        .order_by(SkillRun.id.desc())
    )
    if run is None:
        return None
    context = run.context_snapshot or {}
    if (
        context.get("simple_step_key") != task.step_key
        or context.get("simple_activation_no") != task.activation_no
        or context.get("simple_assignee_id") != task.assignee_id
        or context.get("simple_archived")
    ):
        return None
    return run


async def _collect_revision_refs(
    db: AsyncSession, execution: SimpleStepExecution
) -> set[int]:
    """Union of upstream confirmations a step actually consumed.

    Only the *effective* chain counts: the confirmed revision when the step is
    completed, otherwise the revision currently on screen.  Superseded
    revisions in the same execution keep their historical references for
    audit, but they must not mark a downstream step stale after a newer
    confirmation already stopped depending on the replaced upstream.

    ``input_snapshot`` adds the references of an attempt that is still in
    flight, which is what a reopened upstream has to invalidate.
    """
    rows = list(
        await db.scalars(
            select(SimpleStepRevision).where(
                SimpleStepRevision.execution_id == execution.id
            )
        )
    )
    by_id = {row.id: row for row in rows}
    refs: set[int] = set()
    head_id = (
        execution.confirmed_revision_id
        if execution.confirmed_revision_id is not None
        else execution.current_revision_id
    )
    seen: set[int] = set()
    while isinstance(head_id, int) and head_id not in seen:
        seen.add(head_id)
        row = by_id.get(head_id)
        if row is None:
            break
        structured = row.source_revision_refs
        if not isinstance(structured, dict):
            break
        upstream = structured.get("upstream")
        if isinstance(upstream, dict):
            refs.update(
                value for value in upstream.values() if isinstance(value, int)
            )
        head_id = structured.get("base_revision_id")
    snapshot_upstream = (execution.input_snapshot or {}).get(
        "upstream_revisions"
    ) or {}
    if isinstance(snapshot_upstream, dict):
        refs.update(
            value.get("revision_id")
            for value in snapshot_upstream.values()
            if isinstance(value, dict)
            and isinstance(value.get("revision_id"), int)
        )
    return refs


async def _replace_stale_run(
    db: AsyncSession,
    report_case: ReportCase,
    task: StepTask,
    execution: SimpleStepExecution,
    tasks: list[StepTask],
    run: SkillRun,
) -> Optional[int]:
    """Start the retry that replaces a failed run.

    Returns the attempt number of the retry that is now expected to produce
    the next revision, or ``None`` when a concurrent worker already replaced
    the failure and this worker must leave the execution alone.
    """
    snapshot = execution.input_snapshot or {}
    current_attempt = snapshot.get("attempt_no")
    if not isinstance(current_attempt, int) or current_attempt < 1:
        current_attempt = 1
    next_attempt = current_attempt + 1
    store_error = (run.error or "simple_skill_run_failed")[:2000]

    in_flight = await db.scalar(
        select(SkillRun)
        .where(
            SkillRun.step_task_id == task.id,
            SkillRun.target_type == SIMPLE_STEP_TARGET_TYPE,
            SkillRun.status.in_(("PENDING", "RUNNING")),
        )
        .order_by(SkillRun.id)
    )
    if in_flight is not None:
        return None

    (
        revision_type,
        base_revision,
        feedback_text,
        retry_attempt,
        upstream,
        recover_stale,
    ) = await _resolve_retry_parameters(db, report_case, tasks, execution, task)
    if retry_attempt != current_attempt:
        # Another worker already replaced this failure.
        return None

    try:
        async with db.begin_nested():
            _execution, created = await _start_run(
                db,
                report_case,
                task,
                execution,
                revision_type=revision_type,
                base_revision=base_revision,
                tasks=tasks,
                feedback_text=feedback_text,
                idempotency_key=_auto_run_key(execution, next_attempt),
                actor=None,
                upstream=upstream,
                attempt_no=next_attempt,
                recover_stale=recover_stale,
                allow_failed_state=True,
                last_error=store_error,
                frozen_run=run if not recover_stale else None,
            )
    except IntegrityError:
        return None
    if not created:
        # Another worker already replayed this attempt; leaving the execution
        # untouched is what keeps the failure bookkeeping consistent.
        return None
    return next_attempt


async def _replay_run(
    db: AsyncSession,
    task: StepTask,
    execution: SimpleStepExecution,
    idempotency_key: str,
    *,
    requested_mode: Any = _UNSET,
    requested_base_revision_id: Any = _UNSET,
    requested_feedback_text: Any = _UNSET,
    expected_recover_stale: Optional[bool] = None,
) -> Optional[SkillRun]:
    """Return the run an idempotent generation request already created.

    An idempotency key identifies one exact request, not merely one step.  The
    stored request scope is compared field by field so reusing a key with a
    different mode, base revision, feedback, activation, owner or recovery
    plan is rejected instead of silently returning unrelated work.
    """
    run = await db.scalar(
        select(SkillRun).where(SkillRun.idempotency_key == idempotency_key)
    )
    if run is None:
        return None
    context = run.context_snapshot if isinstance(run.context_snapshot, dict) else {}
    if (
        run.target_type != SIMPLE_STEP_TARGET_TYPE
        or run.step_task_id != task.id
        or run.report_case_id != execution.report_case_id
        or context.get("simple_step_key") != task.step_key
        or context.get("simple_activation_no") != execution.activation_no
        or context.get("simple_assignee_id") != task.assignee_id
    ):
        raise ValueError("simple_generation_idempotency_conflict")
    recorded = context.get("simple_request_scope")
    if not isinstance(recorded, dict):
        raise ValueError("simple_generation_idempotency_conflict")
    scope = recorded.get("scope")
    requested = recorded.get("requested")
    if not isinstance(scope, dict) or not isinstance(requested, dict):
        raise ValueError("simple_generation_idempotency_conflict")
    stored_fingerprint = context.get("simple_input_fingerprint")
    if (
        not isinstance(stored_fingerprint, str)
        or _fingerprint(scope) != stored_fingerprint
    ):
        # The stored scope no longer reproduces the recorded input
        # fingerprint, so the key cannot be trusted as a replay.
        raise ValueError("simple_generation_idempotency_conflict")
    scope_expectations = {
        "step_key": task.step_key,
        "activation_no": execution.activation_no,
        "assignee_id": task.assignee_id,
        "revision_type": context.get("simple_revision_type"),
        "base_revision_id": context.get("simple_base_revision_id"),
    }
    for key, expected in scope_expectations.items():
        if scope.get(key) != expected:
            raise ValueError("simple_generation_idempotency_conflict")
    if bool(scope.get("recover_stale")) != bool(
        context.get("simple_recover_stale")
    ):
        raise ValueError("simple_generation_idempotency_conflict")
    if set(requested) != {
        "requested_mode",
        "requested_base_revision_id",
        "requested_feedback_text",
    }:
        raise ValueError("simple_generation_idempotency_conflict")
    if (
        requested_mode is not _UNSET
        and requested.get("requested_mode") != requested_mode
    ):
        raise ValueError("simple_generation_idempotency_conflict")
    if (
        requested_base_revision_id is not _UNSET
        and requested.get("requested_base_revision_id")
        != requested_base_revision_id
    ):
        raise ValueError("simple_generation_idempotency_conflict")
    if (
        requested_feedback_text is not _UNSET
        and _normalized_text(requested.get("requested_feedback_text"))
        != _normalized_text(requested_feedback_text)
    ):
        raise ValueError("simple_generation_idempotency_conflict")
    if (
        expected_recover_stale is not None
        and bool(scope.get("recover_stale"))
        != bool(expected_recover_stale)
    ):
        # A recovery run clears ``dependency_status`` the moment it starts,
        # so replaying that same request legitimately observes the
        # post-recovery state.  The opposite direction stays a conflict.
        if not (scope.get("recover_stale") and not expected_recover_stale):
            raise ValueError("simple_generation_idempotency_conflict")
    return run


def _auto_run_key(execution: SimpleStepExecution, attempt_no: int) -> str:
    """Idempotency key for one automatic generation attempt of one activation."""
    return (
        f"simple-auto:{execution.id}:{execution.activation_no}:{attempt_no}"
    )


def _input_snapshot(
    report_case: ReportCase,
    task: StepTask,
    base_revision: Optional[SimpleStepRevision],
    upstream: dict[str, dict[str, Any]],
    *,
    revision_type: str,
    feedback_text: Optional[str],
    attempt_no: int = 1,
) -> dict[str, Any]:
    application = report_case.application_snapshot or {}
    return {
        "contract": "simple_ai_step_input_v1",
        "revision_type": revision_type,
        "step_key": task.step_key,
        "attempt_no": attempt_no,
        "generation_profile": (task.config_snapshot or {}).get(
            "generation_profile"
        ),
        "user_info": deepcopy(application.get("profile") or {}),
        "report_context": deepcopy(application.get("context") or {}),
        "base_revision": (
            {
                "revision_id": base_revision.id,
                "revision_no": base_revision.revision_no,
                "content": base_revision.content,
                "structured_content": base_revision.structured_content,
            }
            if base_revision is not None
            else None
        ),
        "upstream_revisions": deepcopy(upstream),
        "feedback_text": feedback_text,
    }


async def _record_decision(
    db: AsyncSession,
    execution: SimpleStepExecution,
    *,
    target_revision_id: int,
    decision: str,
    actor: User,
    idempotency_key: str,
    feedback_text: Optional[str] = None,
    review_mode: str = "OWNER",
    on_behalf_of_user_id: Optional[int] = None,
    reviewer_id: Optional[int] = None,
) -> SimpleReviewDecision:
    if review_mode not in {"OWNER", "ADMIN", "DELEGATED"}:
        raise ValueError("simple_review_mode_invalid")
    if review_mode == "OWNER" and on_behalf_of_user_id is not None:
        raise ValueError("simple_review_delegation_invalid")
    if review_mode != "OWNER" and on_behalf_of_user_id is None:
        raise ValueError("simple_review_delegation_required")
    expected_reviewer_id = (
        on_behalf_of_user_id
        if review_mode != "OWNER" and reviewer_id is None
        else (reviewer_id or actor.id)
    )
    existing = await db.scalar(
        select(SimpleReviewDecision).where(
            SimpleReviewDecision.execution_id == execution.id,
            SimpleReviewDecision.idempotency_key == idempotency_key,
        )
    )
    normalized_feedback = _normalized_text(feedback_text)
    if existing is not None:
        if (
            existing.decision != decision
            or existing.target_revision_id != target_revision_id
            or existing.feedback_text != normalized_feedback
            or existing.review_mode != review_mode
            or existing.reviewer_id != expected_reviewer_id
            or existing.operator_id != actor.id
            or existing.on_behalf_of_user_id != on_behalf_of_user_id
        ):
            raise ValueError("simple_review_idempotency_conflict")
        return existing
    target = await db.get(SimpleStepRevision, target_revision_id)
    if target is None or target.execution_id != execution.id:
        # Every decision must point at an immutable revision of the execution
        # it reviews.  Guarding here keeps a forged or stale revision id from
        # creating an audit row that references someone else's content.
        raise ValueError("simple_revision_not_found")
    decision_row = SimpleReviewDecision(
        execution_id=execution.id,
        target_revision_id=target_revision_id,
        decision=decision,
        feedback_text=normalized_feedback,
        reviewer_id=expected_reviewer_id,
        review_mode=review_mode,
        operator_id=actor.id,
        on_behalf_of_user_id=on_behalf_of_user_id,
        idempotency_key=idempotency_key,
        created_at=_now(),
    )
    db.add(decision_row)
    await db.flush()
    return decision_row


async def _queue_step_run(
    db: AsyncSession,
    report_case: ReportCase,
    task: StepTask,
    execution: SimpleStepExecution,
    *,
    revision_type: str,
    base_revision: Optional[SimpleStepRevision],
    upstream: dict[str, dict[str, Any]],
    feedback_text: Optional[str],
    idempotency_key: str,
    attempt_no: int = 1,
    recover_stale: bool = False,
    requested_mode: Any = _UNSET,
    requested_base_revision_id: Any = _UNSET,
    requested_feedback_text: Any = _UNSET,
    frozen_run: Optional[SkillRun] = None,
) -> tuple[SkillRun, bool, str]:
    from app.application.skill_runtime import _queue_run

    config = step_simple_step_config(task)
    version_id = (task.config_snapshot or {}).get("skill_version_id")
    if not isinstance(version_id, int):
        raise ValueError("step_skill_not_configured")
    input_snapshot = _input_snapshot(
        report_case,
        task,
        base_revision,
        upstream,
        revision_type=revision_type,
        feedback_text=feedback_text,
        attempt_no=attempt_no,
    )
    scope = _fingerprint_scope(
        report_case,
        task,
        execution,
        base_revision,
        feedback_text,
        upstream,
        revision_type=revision_type,
        recover_stale=recover_stale,
    )
    input_fingerprint = _fingerprint(scope)
    return await _queue_run(
        db,
        version_id=version_id,
        idempotency_key=idempotency_key,
        input_data=input_snapshot,
        runtime_instruction=None,
        target_type=SIMPLE_STEP_TARGET_TYPE,
        target_key=task.step_key,
        report_case=report_case,
        step=task,
        context_metadata={
            "simple_protocol": SIMPLE_PROTOCOL_AI_ASSISTED,
            "simple_step_key": task.step_key,
            "simple_activation_no": execution.activation_no,
            "simple_revision_type": revision_type,
            "simple_base_revision_id": (
                base_revision.id if base_revision is not None else None
            ),
            "simple_input_fingerprint": input_fingerprint,
            "simple_assignee_id": task.assignee_id,
            "simple_generation_profile": config.get("generation_profile"),
            "simple_attempt_no": attempt_no,
            "simple_recover_stale": recover_stale,
            "simple_request_scope": {
                "requested": {
                    "requested_mode": (
                        revision_type
                        if requested_mode is _UNSET
                        else requested_mode
                    ),
                    "requested_base_revision_id": (
                        base_revision.id if base_revision else None
                    )
                    if requested_base_revision_id is _UNSET
                    else requested_base_revision_id,
                    "requested_feedback_text": _normalized_text(
                        feedback_text
                        if requested_feedback_text is _UNSET
                        else requested_feedback_text
                    ),
                },
                "scope": scope,
            },
        },
        run_type=_RUN_TYPE_BY_REVISION_TYPE[revision_type],
        commit=False,
        frozen_run=frozen_run,
    ) + (input_fingerprint,)


async def _start_run(
    db: AsyncSession,
    report_case: ReportCase,
    task: StepTask,
    execution: SimpleStepExecution,
    *,
    revision_type: str,
    base_revision: Optional[SimpleStepRevision],
    tasks: list[StepTask],
    feedback_text: Optional[str],
    idempotency_key: str,
    actor: Optional[User],
    upstream: Optional[dict[str, dict[str, Any]]] = None,
    attempt_no: int = 1,
    recover_stale: bool = False,
    allow_failed_state: bool = False,
    last_error: Optional[str] = None,
    requested_mode: Any = _UNSET,
    requested_base_revision_id: Any = _UNSET,
    requested_feedback_text: Any = _UNSET,
    frozen_run: Optional[SkillRun] = None,
) -> tuple[SimpleStepExecution, bool]:
    """Queue one generation run for a step.

    Returns the execution plus whether this call created a new run.  An
    idempotent replay reports ``False`` so callers never treat a replayed run
    as a fresh attempt.
    """
    if execution.activation_no != task.activation_no:
        raise ValueError("simple_activation_outdated")
    if task.assignee_id is None:
        raise ValueError("step_unassigned")
    if execution.dependency_status != "CURRENT":
        # A revision that references a replaced upstream confirmation is only
        # recoverable by regenerating it from the latest confirmed upstream
        # revisions.  Revising the stale content in place stays blocked.
        if not recover_stale or revision_type == AI_REVISION:
            raise ValueError("simple_step_dependency_stale")
    if revision_type == INITIAL:
        allowed_states = {"READY", "FAILED"}
        if base_revision is not None:
            raise ValueError("simple_initial_revision_conflict")
    elif revision_type in {AI_REVISION, REGENERATE}:
        allowed_states = {"IN_REVIEW", "FAILED"}
        if base_revision is None or base_revision.id != execution.current_revision_id:
            raise ValueError("simple_revision_outdated")
        if revision_type == AI_REVISION and not (feedback_text or "").strip():
            raise ValueError("simple_feedback_required")
    else:
        raise ValueError("simple_revision_type_invalid")
    if recover_stale:
        allowed_states = {
            "READY",
            "GENERATING",
            "IN_REVIEW",
            "REVISING",
            "FAILED",
            "COMPLETED",
        }
    elif allow_failed_state:
        allowed_states = {
            "FAILED",
            _RUNNING_STATUS_BY_REVISION_TYPE[revision_type],
        }
    if execution.execution_status not in allowed_states:
        raise ValueError(
            "simple_step_not_ready"
            if "READY" in allowed_states
            else "simple_step_not_in_review"
        )

    if upstream is None:
        upstream = await _load_upstream_revisions(db, report_case, tasks, task)
    run, created, input_fingerprint = await _queue_step_run(
        db,
        report_case,
        task,
        execution,
        revision_type=revision_type,
        base_revision=base_revision,
        upstream=upstream,
        feedback_text=feedback_text,
        idempotency_key=idempotency_key,
        attempt_no=attempt_no,
        recover_stale=recover_stale,
        requested_mode=requested_mode,
        requested_base_revision_id=requested_base_revision_id,
        requested_feedback_text=requested_feedback_text,
        frozen_run=frozen_run,
    )
    if not created:
        # Idempotent replay: never restart a run that already exists.
        return execution, False

    execution.execution_status = _RUNNING_STATUS_BY_REVISION_TYPE[revision_type]
    execution.active_skill_run_id = run.id
    execution.input_snapshot = _input_snapshot(
        report_case,
        task,
        base_revision,
        upstream,
        revision_type=revision_type,
        feedback_text=feedback_text,
        attempt_no=attempt_no,
    )
    execution.input_fingerprint = input_fingerprint
    execution.stale_reason = None
    if recover_stale:
        execution.dependency_status = "CURRENT"
    execution.updated_at = _now()
    flag_modified(execution, "input_snapshot")
    task.status = "EXECUTING"
    task.last_error = last_error
    task.started_at = task.started_at or _now()
    task.retry_count = max(0, attempt_no - 1)
    task.updated_at = _now()
    await db.flush()
    return execution, True


async def prepare_ready_step(
    db: AsyncSession, case_id: int, step_task_id: int, activation_no: int
) -> str:
    """React to ``workflow.step.ready`` for an AI-assisted Simple case."""
    report_case, instance, tasks = await _lock_case(db, case_id)
    if instance.status != "RUNNING" or report_case.status in {
        "CANCELLED",
        "DELIVERED",
    }:
        return "inactive"
    task = next((item for item in tasks if item.id == step_task_id), None)
    if task is None or task.activation_no != activation_no:
        return "stale"
    if task.assignee_id is None:
        return "waiting_for_assignee"
    execution = await _lock_execution(db, report_case, task)
    if execution.dependency_status == "STALE":
        current = (
            await db.get(SimpleStepRevision, execution.current_revision_id)
            if execution.current_revision_id
            else None
        )
        revision_type = REGENERATE if current is not None else INITIAL
        if current is None and execution.current_revision_id is not None:
            raise ValueError("simple_revision_not_found")
        attempt_key = (
            f"simple-recover:{execution.id}:{execution.activation_no}:"
            f"{revision_type}"
        )
        replay = await _replay_run(
            db,
            task,
            execution,
            attempt_key,
            requested_mode=revision_type,
            requested_base_revision_id=(
                current.id if current is not None else None
            ),
            requested_feedback_text=None,
            expected_recover_stale=True,
        )
        if replay is not None:
            return "already_started"
        await _start_run(
            db,
            report_case,
            task,
            execution,
            revision_type=revision_type,
            base_revision=current,
            tasks=tasks,
            feedback_text=None,
            idempotency_key=attempt_key,
            actor=None,
            attempt_no=1,
            recover_stale=True,
            requested_mode=revision_type,
            requested_base_revision_id=(
                current.id if current is not None else None
            ),
            requested_feedback_text=None,
        )
        await db.commit()
        return "started"
    if execution.execution_status in {"GENERATING", "REVISING"}:
        return "already_started"
    if execution.execution_status == "IN_REVIEW":
        return "in_review"
    if execution.execution_status == "COMPLETED":
        return "completed"
    if execution.execution_status == "FAILED":
        # Automatic retries are owned by the skill runtime.  A failure that
        # exhausted them waits here for the consultant to retry explicitly.
        return "failed"
    if task.status != "READY":
        return "waiting_for_assignee"
    attempt_no = 1
    attempt_key = _auto_run_key(execution, attempt_no)
    replay = await _replay_run(
        db,
        task,
        execution,
        attempt_key,
        requested_mode=INITIAL,
        requested_base_revision_id=None,
        requested_feedback_text=None,
        expected_recover_stale=False,
    )
    if replay is not None:
        return "already_started"
    await _start_run(
        db,
        report_case,
        task,
        execution,
        revision_type=INITIAL,
        base_revision=None,
        tasks=tasks,
        feedback_text=None,
        idempotency_key=attempt_key,
        actor=None,
        attempt_no=attempt_no,
        requested_mode=INITIAL,
        requested_base_revision_id=None,
        requested_feedback_text=None,
    )
    await db.commit()
    return "started"


async def start_generation(
    db: AsyncSession,
    *,
    case_id: int,
    step_key: str,
    actor: User,
    idempotency_key: str,
    mode: str = INITIAL,
    base_revision_id: Optional[int] = None,
    feedback_text: Optional[str] = None,
    review_mode: Optional[str] = None,
    on_behalf_of_user_id: Optional[int] = None,
) -> SimpleStepExecution:
    """Start, revise or retry generation for one AI Simple step.

    ``mode`` is ``INITIAL`` for the first generation, ``AI_REVISION`` for
    feedback-driven revision and ``REGENERATE`` for a full rewrite of the base
    revision.  Retrying a ``FAILED`` step always resumes the frozen plan of the
    failed attempt, so a retry can never silently switch the revision type,
    base revision or upstream references of an in-flight chain.
    """
    if mode not in {INITIAL, AI_REVISION, REGENERATE}:
        raise ValueError("simple_revision_type_invalid")
    requested_mode = mode
    requested_base_revision_id = base_revision_id
    requested_feedback_text = feedback_text
    report_case, instance, tasks = await _lock_case(db, case_id)
    if instance.status != "RUNNING" or report_case.status in {
        "CANCELLED",
        "DELIVERED",
    }:
        raise ValueError("workflow_not_active")
    task = _find_step(tasks, step_key)
    _authorize_actor(task, actor)
    execution = await _lock_execution(db, report_case, task)
    resolved_mode, resolved_on_behalf = await _resolve_review_identity(
        db,
        task,
        actor,
        review_mode=review_mode,
        on_behalf_of_user_id=on_behalf_of_user_id,
    )
    replay = await _replay_run(
        db,
        task,
        execution,
        idempotency_key,
        requested_mode=requested_mode,
        requested_base_revision_id=requested_base_revision_id,
        requested_feedback_text=requested_feedback_text,
    )
    if replay is not None:
        return execution
    if execution.execution_status in {"GENERATING", "REVISING"}:
        raise ValueError("simple_step_run_in_progress")
    if execution.execution_status == "COMPLETED":
        raise ValueError("simple_step_already_completed")
    if execution.execution_status == "FAILED":
        (
            revision_type,
            base_revision,
            frozen_feedback,
            failed_attempt,
            upstream,
            recover_stale,
        ) = await _resolve_retry_parameters(db, report_case, tasks, execution, task)
        frozen_run = (
            None
            if recover_stale
            else await _latest_failed_run_for_retry(db, task)
        )
        await _start_run(
            db,
            report_case,
            task,
            execution,
            revision_type=revision_type,
            base_revision=base_revision,
            tasks=tasks,
            feedback_text=frozen_feedback,
            idempotency_key=idempotency_key,
            actor=actor,
            upstream=upstream,
            attempt_no=failed_attempt + 1,
            recover_stale=recover_stale,
            allow_failed_state=True,
            requested_mode=requested_mode,
            requested_base_revision_id=requested_base_revision_id,
            requested_feedback_text=requested_feedback_text,
            frozen_run=frozen_run,
        )
        await db.commit()
        await db.refresh(execution)
        return execution

    base_revision = await _base_revision(db, execution, base_revision_id)
    recover_stale = execution.dependency_status == "STALE"
    if recover_stale:
        if mode == AI_REVISION:
            raise ValueError("simple_step_dependency_stale")
        if execution.current_revision_id is not None:
            if base_revision is None or (
                base_revision.id != execution.current_revision_id
            ):
                raise ValueError("simple_revision_outdated")
            mode = REGENERATE
            decision = "REGENERATE"
        else:
            if base_revision is not None:
                raise ValueError("simple_initial_revision_conflict")
            mode = INITIAL
            decision = None
    elif mode == INITIAL:
        if base_revision is not None or execution.current_revision_id:
            raise ValueError("simple_initial_revision_conflict")
        decision = None
    else:
        if base_revision is None or base_revision.id != execution.current_revision_id:
            raise ValueError("simple_revision_outdated")
        if mode == AI_REVISION and not (feedback_text or "").strip():
            raise ValueError("simple_feedback_required")
        decision = "REQUEST_REVISION" if mode == AI_REVISION else "REGENERATE"
    if decision is not None:
        await _record_decision(
            db,
            execution,
            target_revision_id=base_revision.id,
            decision=decision,
            actor=actor,
            idempotency_key=f"decision:{idempotency_key}",
            feedback_text=feedback_text,
            review_mode=resolved_mode,
            on_behalf_of_user_id=resolved_on_behalf,
        )
    await _start_run(
        db,
        report_case,
        task,
        execution,
        revision_type=mode,
        base_revision=base_revision,
        tasks=tasks,
        feedback_text=feedback_text,
        idempotency_key=idempotency_key,
        actor=actor,
        recover_stale=recover_stale,
        requested_mode=requested_mode,
        requested_base_revision_id=requested_base_revision_id,
        requested_feedback_text=requested_feedback_text,
    )
    await db.commit()
    await db.refresh(execution)
    return execution


async def apply_run_result(
    db: AsyncSession, run: SkillRun
) -> Optional[SimpleStepRevision]:
    """Persist a completed Simple run as an immutable revision.

    Returns ``None`` when the run lost its activation, owner, base revision or
    input fingerprint while it was executing.  The stale result is written back
    to the run context for audit and never becomes official content.
    """
    if run.target_type != SIMPLE_STEP_TARGET_TYPE or run.report_case_id is None:
        return None
    existing = await db.scalar(
        select(SimpleStepRevision).where(
            SimpleStepRevision.idempotency_key == f"simple-run-revision:{run.id}"
        )
    )
    if existing is not None:
        return existing
    context = run.context_snapshot or {}
    report_case, _instance, tasks = await _lock_case(db, run.report_case_id)
    task = next((item for item in tasks if item.id == run.step_task_id), None)
    if task is None:
        return None
    execution = await _lock_execution(db, report_case, task)
    revision_type = context.get("simple_revision_type")
    base_revision_id = context.get("simple_base_revision_id")
    stale = (
        report_case.status != "ACTIVE"
        or context.get("simple_step_key") != task.step_key
        or context.get("simple_activation_no") != execution.activation_no
        or context.get("simple_assignee_id") != task.assignee_id
        or context.get("simple_input_fingerprint") != execution.input_fingerprint
        or execution.active_skill_run_id != run.id
        or execution.dependency_status != "CURRENT"
        or revision_type not in {INITIAL, AI_REVISION, REGENERATE}
        or execution.execution_status
        != _RUNNING_STATUS_BY_REVISION_TYPE.get(revision_type)
        or execution.current_revision_id != base_revision_id
    )
    if stale:
        context = dict(context)
        context["simple_archived"] = "obsolete_activation_or_input"
        run.context_snapshot = context
        flag_modified(run, "context_snapshot")
        await db.flush()
        return None

    content, structured = _revision_payload(run)
    if not content and structured is None:
        raise ValueError("simple_revision_content_missing")
    revision = SimpleStepRevision(
        execution_id=execution.id,
        revision_no=await _next_revision_no(db, execution.id),
        revision_type=revision_type,
        parent_revision_id=base_revision_id,
        content=content,
        structured_content=structured,
        source_revision_refs={
            "upstream": {
                key: value["revision_id"]
                for key, value in (
                    (execution.input_snapshot or {}).get("upstream_revisions")
                    or {}
                ).items()
            },
            "base_revision_id": base_revision_id,
        },
        skill_run_id=run.id,
        created_by=None,
        idempotency_key=f"simple-run-revision:{run.id}",
        created_at=_now(),
    )
    db.add(revision)
    await db.flush()
    execution.current_revision_id = revision.id
    execution.execution_status = "IN_REVIEW"
    execution.active_skill_run_id = None
    execution.updated_at = _now()
    task.status = "IN_REVIEW"
    task.last_error = None
    task.updated_at = _now()
    await db.flush()
    return revision


async def record_run_failure(db: AsyncSession, run: SkillRun) -> None:
    """Move a failed Simple run back to a retryable state.

    The first two failures of one activation are retried automatically with
    the same frozen input; later failures stay visible as ``FAILED`` and wait
    for the consultant to retry explicitly.
    """
    if run.target_type != SIMPLE_STEP_TARGET_TYPE or run.report_case_id is None:
        return
    report_case, _instance, tasks = await _lock_case(db, run.report_case_id)
    task = next((item for item in tasks if item.id == run.step_task_id), None)
    if task is None:
        return
    execution = await _lock_execution(db, report_case, task)
    if execution.active_skill_run_id != run.id:
        return
    context = run.context_snapshot or {}
    if context.get("simple_assignee_id") != task.assignee_id:
        # A reassigned step must not let the previous owner's late failure
        # trigger retries or overwrite the new owner's execution state.
        context = dict(context)
        context["simple_archived"] = "obsolete_assignee"
        run.context_snapshot = context
        flag_modified(run, "context_snapshot")
        await db.flush()
        return
    attempt_no = context.get("simple_attempt_no")
    if not isinstance(attempt_no, int) or attempt_no < 1:
        snapshot_attempt = (execution.input_snapshot or {}).get("attempt_no")
        attempt_no = (
            snapshot_attempt
            if isinstance(snapshot_attempt, int) and snapshot_attempt >= 1
            else 1
        )
    error_text = (run.error or "simple_skill_run_failed")[:2000]
    config = step_simple_step_config(task)
    retry_limit = config.get("auto_retry_limit")
    if not isinstance(retry_limit, int) or isinstance(retry_limit, bool):
        retry_limit = SIMPLE_AUTO_RETRY_LIMIT

    next_attempt: Optional[int] = None
    if attempt_no <= retry_limit:
        next_attempt = await _replace_stale_run(
            db, report_case, task, execution, tasks, run
        )
    if next_attempt is not None:
        execution.input_snapshot = {
            **(execution.input_snapshot or {}),
            "last_error": error_text,
        }
        flag_modified(execution, "input_snapshot")
        task.last_error = error_text
        task.updated_at = _now()
        await db.flush()
        return

    execution.execution_status = "FAILED"
    execution.active_skill_run_id = None
    execution.input_snapshot = {
        **(execution.input_snapshot or {}),
        "last_error": error_text,
    }
    execution.updated_at = _now()
    flag_modified(execution, "input_snapshot")
    task.status = "READY"
    task.last_error = error_text
    task.updated_at = _now()
    await db.flush()


async def save_manual_edit(
    db: AsyncSession,
    *,
    case_id: int,
    step_key: str,
    actor: User,
    content: str,
    structured_content: Optional[dict],
    base_revision_id: int,
    idempotency_key: str,
    review_mode: Optional[str] = None,
    on_behalf_of_user_id: Optional[int] = None,
) -> SimpleStepRevision:
    report_case, _instance, tasks = await _lock_case(db, case_id)
    task = _find_step(tasks, step_key)
    resolved_mode, resolved_on_behalf = await _resolve_review_identity(
        db,
        task,
        actor,
        review_mode=review_mode,
        on_behalf_of_user_id=on_behalf_of_user_id,
    )
    execution = await _lock_execution(db, report_case, task)
    text = (content or "").strip()
    existing = await db.scalar(
        select(SimpleStepRevision).where(
            SimpleStepRevision.execution_id == execution.id,
            SimpleStepRevision.idempotency_key == idempotency_key,
        )
    )
    if existing is not None:
        decision = await db.scalar(
            select(SimpleReviewDecision).where(
                SimpleReviewDecision.execution_id == execution.id,
                SimpleReviewDecision.idempotency_key == f"decision:{idempotency_key}",
            )
        )
        expected_reviewer_id = _expected_reviewer_id(
            resolved_mode, actor, resolved_on_behalf
        )
        if (
            existing.revision_type != MANUAL_EDIT
            or existing.parent_revision_id != base_revision_id
            or existing.content != text
            or existing.structured_content != structured_content
            or existing.created_by != actor.id
            or existing.skill_run_id is not None
            or decision is None
            or decision.decision != MANUAL_EDIT
            or decision.target_revision_id != base_revision_id
            or decision.feedback_text is not None
            or decision.review_mode != resolved_mode
            or decision.reviewer_id != expected_reviewer_id
            or decision.operator_id != actor.id
            or decision.on_behalf_of_user_id != resolved_on_behalf
        ):
            raise ValueError("simple_review_idempotency_conflict")
        return existing
    if execution.execution_status != "IN_REVIEW" or task.status != "IN_REVIEW":
        raise ValueError("simple_step_not_in_review")
    if execution.dependency_status != "CURRENT":
        raise ValueError("simple_step_dependency_stale")
    if not isinstance(base_revision_id, int) or base_revision_id <= 0:
        raise ValueError("simple_revision_required")
    base_revision = await _base_revision(db, execution, base_revision_id)
    if base_revision is None or base_revision.id != execution.current_revision_id:
        raise ValueError("simple_revision_outdated")
    if not text and structured_content is None:
        raise ValueError("simple_revision_content_missing")
    revision = SimpleStepRevision(
        execution_id=execution.id,
        revision_no=await _next_revision_no(db, execution.id),
        revision_type=MANUAL_EDIT,
        parent_revision_id=base_revision_id,
        content=text,
        structured_content=structured_content,
        source_revision_refs={
            "upstream": {
                key: value["revision_id"]
                for key, value in (
                    (execution.input_snapshot or {}).get("upstream_revisions") or {}
                ).items()
            },
            "base_revision_id": base_revision_id,
        },
        skill_run_id=None,
        created_by=actor.id,
        idempotency_key=idempotency_key,
        created_at=_now(),
    )
    db.add(revision)
    await db.flush()
    execution.current_revision_id = revision.id
    execution.updated_at = _now()
    await _record_decision(
        db,
        execution,
        target_revision_id=base_revision_id,
        decision=MANUAL_EDIT,
        actor=actor,
        idempotency_key=f"decision:{idempotency_key}",
        feedback_text=None,
        review_mode=resolved_mode,
        on_behalf_of_user_id=resolved_on_behalf,
    )
    await db.commit()
    await db.refresh(revision)
    return revision


async def approve_step(
    db: AsyncSession,
    *,
    case_id: int,
    step_key: str,
    actor: User,
    base_revision_id: int,
    idempotency_key: str,
    final_gate_confirmed: bool = False,
    review_note: Optional[str] = None,
    review_mode: Optional[str] = None,
    on_behalf_of_user_id: Optional[int] = None,
    audit_context: Optional[AuditContext] = None,
) -> SimpleStepExecution:
    report_case, instance, tasks = await _lock_case(db, case_id)
    if instance.status != "RUNNING" or report_case.status in {
        "CANCELLED",
        "DELIVERED",
    }:
        raise ValueError("workflow_not_active")
    task = _find_step(tasks, step_key)
    execution = await _lock_execution(db, report_case, task)
    resolved_mode, resolved_on_behalf = await _resolve_review_identity(
        db,
        task,
        actor,
        review_mode=review_mode,
        on_behalf_of_user_id=on_behalf_of_user_id,
    )
    already = await db.scalar(
        select(SimpleReviewDecision).where(
            SimpleReviewDecision.execution_id == execution.id,
            SimpleReviewDecision.idempotency_key == idempotency_key,
        )
    )
    if already is not None:
        expected_reviewer_id = _expected_reviewer_id(
            resolved_mode, actor, resolved_on_behalf
        )
        if (
            already.decision != "APPROVE"
            or already.target_revision_id != base_revision_id
            or _normalized_text(already.feedback_text)
            != _normalized_text(review_note)
            or already.review_mode != resolved_mode
            or already.reviewer_id != expected_reviewer_id
            or already.operator_id != actor.id
            or already.on_behalf_of_user_id != resolved_on_behalf
        ):
            raise ValueError("simple_review_idempotency_conflict")
        return execution
    if execution.execution_status != "IN_REVIEW":
        raise ValueError("simple_step_not_in_review")
    if base_revision_id != execution.current_revision_id:
        raise ValueError("simple_revision_outdated")
    if execution.dependency_status != "CURRENT":
        raise ValueError("simple_step_dependency_stale")
    config = step_simple_step_config(task)
    is_final = bool(config.get("final_gate"))
    if is_final and not final_gate_confirmed:
        raise ValueError("final_gate_approval_required")
    decision_row = await _record_decision(
        db,
        execution,
        target_revision_id=base_revision_id,
        decision="APPROVE",
        actor=actor,
        idempotency_key=idempotency_key,
        feedback_text=review_note,
        review_mode=resolved_mode,
        on_behalf_of_user_id=resolved_on_behalf,
    )
    execution.execution_status = "COMPLETED"
    execution.confirmed_revision_id = base_revision_id
    execution.updated_at = _now()
    await complete_step(
        db,
        case_id,
        step_key,
        result_json={
            "simple_step_execution_id": execution.id,
            "simple_revision_id": base_revision_id,
        },
        final_gate_verified=is_final,
    )
    await record_audit(
        db,
        actor.id,
        "workflow.simple_step.approve",
        "report_case",
        str(report_case.id),
        details={
            "step_key": step_key,
            "revision_id": base_revision_id,
            "review_mode": resolved_mode,
            "reviewer_id": decision_row.reviewer_id,
            "operator_id": decision_row.operator_id,
            "on_behalf_of_user_id": decision_row.on_behalf_of_user_id,
        },
        audit_context=audit_context,
    )
    await db.commit()
    await db.refresh(execution)
    return execution


async def reopen_step(
    db: AsyncSession,
    *,
    case_id: int,
    step_key: str,
    actor: User,
    reason: Optional[str] = None,
    idempotency_key: Optional[str] = None,
    review_mode: Optional[str] = None,
    on_behalf_of_user_id: Optional[int] = None,
    audit_context: Optional[AuditContext] = None,
) -> SimpleStepExecution:
    """Reopen a completed step and invalidate the downstream it fed."""
    report_case, instance, tasks = await _lock_case(db, case_id)
    if report_case.status in {"CANCELLED", "DELIVERED"}:
        raise ValueError("workflow_not_active")
    task = _find_step(tasks, step_key)
    resolved_mode, resolved_on_behalf = await _resolve_review_identity(
        db,
        task,
        actor,
        review_mode=review_mode,
        on_behalf_of_user_id=on_behalf_of_user_id,
    )
    execution = await _lock_execution(db, report_case, task)
    key = idempotency_key or f"reopen:{execution.id}:{execution.activation_no}"
    existing = await db.scalar(
        select(SimpleReviewDecision).where(
            SimpleReviewDecision.execution_id == execution.id,
            SimpleReviewDecision.idempotency_key == key,
        )
    )
    if existing is not None:
        # The reopen already happened; replaying the request must not bump the
        # activation counter or invalidate the downstream a second time.
        expected_reviewer_id = _expected_reviewer_id(
            resolved_mode, actor, resolved_on_behalf
        )
        target_revision = (
            await db.get(SimpleStepRevision, existing.target_revision_id)
            if existing.target_revision_id is not None
            else None
        )
        if (
            existing.decision != "REOPEN"
            or target_revision is None
            or target_revision.execution_id != execution.id
            or _normalized_text(existing.feedback_text) != _normalized_text(reason)
            or existing.review_mode != resolved_mode
            or existing.reviewer_id != expected_reviewer_id
            or existing.operator_id != actor.id
            or existing.on_behalf_of_user_id != resolved_on_behalf
        ):
            raise ValueError("simple_review_idempotency_conflict")
        return execution
    if execution.execution_status != "COMPLETED":
        raise ValueError("simple_step_not_completed")
    confirmed_revision_id = execution.confirmed_revision_id
    if confirmed_revision_id is None:
        raise ValueError("simple_step_not_completed")
    await _record_decision(
        db,
        execution,
        target_revision_id=confirmed_revision_id,
        decision="REOPEN",
        actor=actor,
        idempotency_key=key,
        feedback_text=reason,
        review_mode=resolved_mode,
        on_behalf_of_user_id=resolved_on_behalf,
    )
    now = _now()

    downstream = [item for item in tasks if item.sequence_no > task.sequence_no]
    for item in downstream:
        downstream_execution = await _lock_execution(db, report_case, item)
        references_old = confirmed_revision_id in await _collect_revision_refs(
            db, downstream_execution
        )
        if not references_old:
            continue
        if item.status != "PENDING":
            item.status = "PENDING"
        item.activated_at = None
        item.started_at = None
        item.completed_at = None
        item.result_json = None
        item.last_error = None
        item.retry_count = 0
        item.updated_at = now
        downstream_execution.execution_status = "READY"
        downstream_execution.confirmed_revision_id = None
        downstream_execution.active_skill_run_id = None
        downstream_execution.input_fingerprint = None
        downstream_execution.dependency_status = "STALE"
        downstream_execution.stale_reason = (
            f"upstream:{step_key}:confirmed_revision:{confirmed_revision_id}"
        )
        downstream_execution.updated_at = now

    execution.execution_status = "READY"
    execution.confirmed_revision_id = None
    execution.current_revision_id = None
    execution.active_skill_run_id = None
    execution.activation_no += 1
    execution.input_snapshot = {}
    execution.input_fingerprint = None
    execution.stale_reason = None
    execution.updated_at = now
    flag_modified(execution, "input_snapshot")
    if task.status != "COMPLETED":
        raise ValueError("simple_step_not_completed")
    task.status = "READY"
    task.activation_no += 1
    task.activated_at = now
    task.started_at = None
    task.result_json = None
    task.completed_at = None
    task.last_error = None
    task.retry_count = 0
    task.updated_at = now
    if instance.status == "COMPLETED":
        instance.status = "RUNNING"
        instance.completed_at = None
        instance.updated_at = now
    report_case.status = "ACTIVE"
    report_case.updated_at = now
    # Reopening is the AI equivalent of the legacy rewind: the step is live
    # again, so the ready event has to be emitted for the first regeneration
    # of the new activation.  Without it the step would stay READY until a
    # human explicitly pressed generate.
    await enqueue_step_ready(db, report_case, task)
    await record_audit(
        db,
        actor.id,
        "workflow.simple_step.reopen",
        "report_case",
        str(report_case.id),
        details={
            "step_key": step_key,
            "reason": (reason or "")[:500],
            "review_mode": resolved_mode,
            "operator_id": actor.id,
            "on_behalf_of_user_id": resolved_on_behalf,
        },
        audit_context=audit_context,
    )
    await db.commit()
    await db.refresh(execution)
    return execution


def _serialize_revision(
    revision: Optional[SimpleStepRevision],
) -> Optional[dict[str, Any]]:
    if revision is None:
        return None
    return {
        "id": revision.id,
        "revision_no": revision.revision_no,
        "revision_type": revision.revision_type,
        "parent_revision_id": revision.parent_revision_id,
        "content": revision.content,
        "structured_content": revision.structured_content,
        "source_revision_refs": revision.source_revision_refs,
        "skill_run_id": revision.skill_run_id,
        "created_by": revision.created_by,
        "created_at": revision.created_at.isoformat()
        if revision.created_at
        else None,
    }


def _serialize_execution(execution: SimpleStepExecution) -> dict[str, Any]:
    return {
        "id": execution.id,
        "report_case_id": execution.report_case_id,
        "step_task_id": execution.step_task_id,
        "step_key": execution.step_key,
        "execution_status": execution.execution_status,
        "dependency_status": execution.dependency_status,
        "activation_no": execution.activation_no,
        "current_revision_id": execution.current_revision_id,
        "confirmed_revision_id": execution.confirmed_revision_id,
        "active_skill_run_id": execution.active_skill_run_id,
        "input_fingerprint": execution.input_fingerprint,
        "stale_reason": execution.stale_reason,
        "last_error": (execution.input_snapshot or {}).get("last_error"),
        "created_at": execution.created_at.isoformat()
        if execution.created_at
        else None,
        "updated_at": execution.updated_at.isoformat()
        if execution.updated_at
        else None,
    }


async def step_state(db: AsyncSession, case_id: int, step_key: str) -> dict:
    """Return the JSON-serializable state of one AI-assisted Simple step."""
    report_case, _instance, tasks = await _lock_case(db, case_id)
    task = _find_step(tasks, step_key)
    execution = await _lock_execution(db, report_case, task)
    current = (
        await db.get(SimpleStepRevision, execution.current_revision_id)
        if execution.current_revision_id
        else None
    )
    confirmed = (
        await db.get(SimpleStepRevision, execution.confirmed_revision_id)
        if execution.confirmed_revision_id
        else None
    )
    return {
        "step_key": task.step_key,
        "step_name": _step_name(task.step_key),
        "task_status": task.status,
        "last_error": task.last_error,
        "execution": _serialize_execution(execution),
        "current_revision": _serialize_revision(current),
        "confirmed_revision": _serialize_revision(confirmed),
    }


async def list_revisions(
    db: AsyncSession, case_id: int, step_key: str
) -> list[SimpleStepRevision]:
    report_case, _instance, tasks = await _lock_case(db, case_id)
    task = _find_step(tasks, step_key)
    execution = await _lock_execution(db, report_case, task)
    return list(
        await db.scalars(
            select(SimpleStepRevision)
            .where(SimpleStepRevision.execution_id == execution.id)
            .order_by(SimpleStepRevision.revision_no)
        )
    )


async def quality_state(db: AsyncSession, case_id: int) -> dict:
    """Return the current S6 quality snapshot for an AI-assisted case."""
    report_case, _instance, tasks = await _lock_case(db, case_id)
    task = _find_step(tasks, "S6")
    execution = await _lock_execution(db, report_case, task)
    revision = (
        await db.get(SimpleStepRevision, execution.current_revision_id)
        if execution.current_revision_id
        else None
    )
    structured = (revision.structured_content or {}) if revision else {}
    return {
        "step_key": "S6",
        "execution_status": execution.execution_status,
        "dependency_status": execution.dependency_status,
        "revision_id": revision.id if revision else None,
        "quality": structured.get("quality") if isinstance(structured, dict) else None,
        # Phase 1 exposes no hard-blocking rules yet; the programmatic gate
        # lands with the phase 3 quality contract.
        "hard_blocks": [],
        "validator_findings": (
            structured.get("findings") if isinstance(structured, dict) else None
        ),
    }
